### ISSUE TITLE
RuntimeError: cuDNN version incompatibility

### ISSUE THREAD

**Issue by bulade0** [YoungSeng/Interspeech2022#16]
Traceback (most recent call last):
  File "demo.py", line 18, in <module>
    G1 = Generator_MI(hparams_, use_VQCPC, use_VQCPC_2).eval().to(device)
  File "/home/zhaofeiyu/.conda/envs/srd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 927, in to
    return self._apply(convert)
  File "/home/zhaofeiyu/.conda/envs/srd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/home/zhaofeiyu/.conda/envs/srd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/home/zhaofeiyu/.conda/envs/srd/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 189, in _apply
    self.flatten_parameters()
  File "/home/zhaofeiyu/.conda/envs/srd/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 154, in flatten_parameters
    not torch.backends.cudnn.is_acceptable(fw.data)):
  File "/home/zhaofeiyu/.conda/envs/srd/lib/python3.8/site-packages/torch/backends/cudnn/__init__.py", line 95, in is_acceptable
    if not _init():
  File "/home/zhaofeiyu/.conda/envs/srd/lib/python3.8/site-packages/torch/backends/cudnn/__init__.py", line 50, in _init
    raise RuntimeError(f'{base_error_msg}'
RuntimeError: cuDNN version incompatibility: PyTorch was compiled  against (8, 3, 2) but found runtime version (8, 2, 1). PyTorch already comes bundled with cuDNN. One option to resolving this error is to ensure PyTorch can find the bundled cuDNN.Looks like your LD_LIBRARY_PATH contains incompatible version of cudnnPlease either remove it from the path or install cudnn (8, 3, 2)

**Comment by YoungSeng** [comment]
Hi, this seems to be a problem with your cuda version.

I will give you two suggestions for debugging:
1. write a simple model yourself, or just move a tensor to the cuda device to see if it works.
2. change the device to cpu to see if the model itself is the problem and can be loaded properly.

Hope it helps you.
