### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

### ISSUE THREAD

**Issue by zhao1025** [YoungSeng/Interspeech2022#17]
Hello, could you help me solve this issue?
Traceback (most recent call last):
  File "demo.py", line 83, in <module>
    f0_pred = P(uttr_org_pad, f0_trg_onehot)[0]
  File "/home/zhaofeiyu/.conda/envs/srd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhaofeiyu/data/SRD-VC-master/My_model/model.py", line 447, in forward
    mel_outputs = self.decoder(encoder_outputs)
  File "/home/zhaofeiyu/.conda/envs/srd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhaofeiyu/data/SRD-VC-master/My_model/model.py", line 309, in forward
    decoder_output = self.linear_projection(outputs)
  File "/home/zhaofeiyu/.conda/envs/srd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhaofeiyu/data/SRD-VC-master/My_model/model.py", line 18, in forward
    return self.linear_layer(x)
  File "/home/zhaofeiyu/.conda/envs/srd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhaofeiyu/.conda/envs/srd/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

**Comment by YoungSeng** [comment]
Possible causes:
1. The shape dimensions don't match, double check and verify.
2. The variables are not on the same device, try adding os.environ['CUDA_VISIBLE_DEVICES'] = '1' at the beginning of the .py file and setting device='cuda:1' to these actions.
3. The pytorch and cuda versions do not match.
